"use client";
import {useEffect,useState} from "react";

type Design={id:string;name:string;productType:string;basePrice:number;imageUrl:string;locked:boolean;provider:"mock"|"openai"};
type Variant={id:string;tier:string;size:string;priceDelta:number;productionDays:number};
type CatalogProduct={id:string;name:string;basePrice:number;inventoryMode:string;status:string;imageUrl:string|null;variants:Variant[]};
const storeSamples=[{name:"Midnight Signal Tee",mark:"D//01"},{name:"Protocol Hoodie",mark:"D//02"},{name:"Node Runner Cap",mark:"D//03"}];
const B58="123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
function encodeBase58(source:Uint8Array){if(!source.length)return"";const digits=[0];for(const byte of source){let carry=byte;for(let i=0;i<digits.length;i++){carry+=digits[i]<<8;digits[i]=carry%58;carry=(carry/58)|0}while(carry){digits.push(carry%58);carry=(carry/58)|0}}let result="";for(let i=0;source[i]===0&&i<source.length-1;i++)result+="1";for(let i=digits.length-1;i>=0;i--)result+=B58[digits[i]];return result}

export default function Home(){
 const [tab,setTab]=useState("Studio"),[wallet,setWallet]=useState(false),[toast,setToast]=useState(""),[shop,setShop]=useState(false);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};
 const connectWallet=async()=>{try{const w=window as any;const provider=w.phantom?.solana||w.solana||w.solflare;if(!provider?.connect||!provider?.signMessage)throw new Error("Install Phantom or Solflare, then refresh.");const connection=await provider.connect();const publicKey=(connection.publicKey||provider.publicKey).toString();const challenge=await fetch("/api/auth/challenge",{method:"POST"});const {message}=await challenge.json();const signed=await provider.signMessage(new TextEncoder().encode(message),"utf8");const signature=signed.signature instanceof Uint8Array?signed.signature:new Uint8Array(signed.signature);const verified=await fetch("/api/auth/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({wallet:publicKey,signature:encodeBase58(signature),message})});const data=await verified.json();if(!verified.ok)throw new Error(data.error||"Wallet sign-in failed");setWallet(true);notify("Wallet verified — welcome to your project")}catch(error){notify(error instanceof Error?error.message:"Wallet connection failed")}};
 const nav=["Studio","Products","Storefront","Orders","Payouts"];
 return <main><header><button className="brand" onClick={()=>setTab("Studio")}><i>D</i> DESIGNOIRS</button><div className="project"><b>N</b><span><small>PROJECT</small>NIGHTNODE</span>⌄</div><div className="headRight"><em>● AI READY</em><button className="wallet" onClick={connectWallet}>{wallet?"Wallet verified":"Connect wallet"}</button></div></header>
 <aside><nav>{nav.map((n,i)=><button key={n} className={tab===n?"active":""} onClick={()=>setTab(n)}><span>{["✦","▦","◫","≡","↗"][i]}</span>{n}</button>)}</nav><div className="provider"><small>FULFILLMENT</small><p><b>PF</b><span>Printful<small>Sandbox connected</small></span><i>●</i></p><button>⚙ Settings</button></div></aside>
 <section className="workspace">{tab==="Studio"?<Studio notify={notify}/>:tab==="Products"?<Products notify={notify}/>:tab==="Storefront"?<Storefront notify={notify} open={()=>setShop(true)}/>:tab==="Orders"?<Orders notify={notify}/>:<Payouts notify={notify}/>}</section>
 {toast&&<div className="toast">✓ {toast}</div>}{shop&&<Shop close={()=>setShop(false)} wallet={wallet} connect={connectWallet} notify={notify}/>}</main>
}

function Head({eyebrow,title,text,children}:any){return <div className="pageHead"><div><p>{eyebrow}</p><h1>{title}</h1><span>{text}</span></div>{children}</div>}
function Studio({notify}:any){
 const [brief,setBrief]=useState("A midnight streetwear capsule inspired by validator nodes, brutalist typography and electric violet light."),[loading,setLoading]=useState(false),[designs,setDesigns]=useState<Design[]>([]),[error,setError]=useState(""),[mode,setMode]=useState<"mock"|"openai">("mock");
 const generate=async()=>{setLoading(true);setError("");try{const response=await fetch("/api/studio/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brief,assetRefs:[],productTypes:["tee","hoodie","hat","beanie"]})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Generation failed");setDesigns(data.designs);setMode(data.mode);notify(`${data.designs.length} fresh directions generated`)}catch(e){setError(e instanceof Error?e.message:"Generation failed")}finally{setLoading(false)}};
 const lock=async(design:Design)=>{try{const response=await fetch("/api/studio/lock",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetId:design.id})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not lock design");setDesigns(items=>items.map(item=>item.id===design.id?{...item,locked:true}:item));notify(`${design.name} added to Products`)}catch(e){setError(e instanceof Error?e.message:"Could not save design")}};
 return <><Head eyebrow="AI COLLECTION STUDIO" title="Spray the idea. Ship the drop." text="Every generation is saved to your project. Lock the winners into a real catalog."><button className="primary spray" disabled={loading} onClick={generate}>✦ {loading?"Painting the walls…":"Generate collection"}</button></Head><div className="studio"><div className="panel direction"><Title n="01" title="Creative direction" sub="Give the model context"/><label>BRAND ASSETS</label><div className="assets"><b>N</b><button onClick={()=>notify("Upload endpoint is next in the production checklist")}><strong>＋ Add assets</strong><small>PNG, SVG, JPG · up to 20MB</small></button></div><label>COLLECTION BRIEF</label><textarea value={brief} onChange={e=>setBrief(e.target.value)}/><div className="chips"><button onClick={()=>setBrief(brief+" Oversized graffiti graphics.")}>Oversized graphics</button><button onClick={()=>setBrief(brief+" Monochrome spray-paint palette.")}>Monochrome</button><button onClick={()=>setBrief(brief+" Embroidered tag detail.")}>Embroidery</button></div><div className="model">✦ <span><small>IMAGE ENGINE</small><b>{mode==="openai"?"GPT Image 2":"Graffiti mock generator"}</b></span><i>{loading?"Working":"Ready"}</i></div></div><div className="panel results"><Title n="02" title="Generated directions" sub={designs.length?`${designs.length} real saved assets · lock to catalog`:"Your wall is clean — generate the first drop"}/>{error&&<div className="error">⚠ {error}</div>}{loading?<LoadingCards/>:designs.length?<div className="productGrid">{designs.map(p=><Card key={p.id} p={p} toggle={()=>lock(p)}/>)}</div>:<div className="emptyWall"><b>YOUR NEXT DROP<br/>STARTS HERE</b><span>Write the lore. Pick the energy. Hit generate.</span></div>}<div className="refine"><input placeholder="Try ‘make the back graphic louder…’"/><button onClick={()=>notify("Refinement will use the next generation brief")}>Remix prompt ↗</button></div></div></div></>}
function Title({n,title,sub}:any){return <div className="title"><em>{n}</em><span><b>{title}</b><small>{sub}</small></span></div>}
function Card({p,toggle}:any){return <article className="card"><div className="art generated"><img src={p.imageUrl} alt={`${p.name} ${p.productType} mockup`}/><span className="assetTag">{p.provider==="openai"?"AI":"MOCK"} // {p.productType}</span><button className={p.locked?"locked":""} disabled={p.locked} onClick={toggle}>{p.locked?"◆ IN CATALOG":"◇ LOCK IT"}</button></div><footer><span><b>{p.name}</b><small>{p.productType} · saved asset</small></span><em>from ${p.basePrice}</em></footer></article>}
function LoadingCards(){return <div className="productGrid">{[0,1,2,3].map(i=><div className="skeleton" key={i}><i/><b/><span/></div>)}</div>}
function Products({notify}:any){const [items,setItems]=useState<CatalogProduct[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{setLoading(true);try{const r=await fetch("/api/products");const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not load products");setItems(data.products)}catch(e){setError(e instanceof Error?e.message:"Could not load products")}finally{setLoading(false)}};useEffect(()=>{load()},[]);const variants=items.reduce((n,p)=>n+p.variants.length,0);return <><Head eyebrow="CATALOG" title="Products & variants" text="Everything here was locked from Studio and loaded from your project database."><button className="primary" onClick={()=>{notify("Generate and lock a Studio design to add products")}}>＋ Add via Studio</button></Head><Stats products={items.length} variants={variants}/>{error&&<div className="error">⚠ {error}</div>}<div className="table"><div className="row th"><span>PRODUCT</span><span>TIERS</span><span>SIZES</span><span>MODE</span><span>STATUS</span></div>{loading?<div className="catalogLoading">Loading your catalog…</div>:items.length?items.map(p=>{const tiers=[...new Set(p.variants.map(v=>v.tier))];const sizes=[...new Set(p.variants.map(v=>v.size))];const premium=p.variants.find(v=>v.tier==="Premium");return <div className="row" key={p.id}><span className="product">{p.imageUrl?<img src={p.imageUrl} alt=""/>:<i>NEW</i>}<b>{p.name}<small>${p.basePrice} base</small></b></span><span>{tiers.map(t=><em key={t}>{t}{t==="Premium"&&premium?` +$${premium.priceDelta}`:""}</em>)}</span><span>{sizes.join(", ")}</span><span>{p.inventoryMode}</span><strong>● {p.status}</strong></div>}):<div className="emptyCatalog"><b>NO PRODUCTS YET</b><span>Generate a collection in Studio and lock your favorite design.</span></div>}</div></>}
function Stats({products=0,variants=0}:any){return <div className="stats">{[[String(products),"Saved products"],[String(variants),"Real variants"],["2","Material tiers"],["3–6d","Production"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div>}
function Storefront({notify,open}:any){const code='<script src="https://embed.designoirs.com/v1.js" data-store="nightnode"></script>';return <><Head eyebrow="STORE BUILDER" title="Your brand. Their site." text="Configure the embedded storefront, then paste one line into any website."><button className="outline" onClick={open}>Customer preview ↗</button></Head><div className="builder"><div className="panel form"><h2>Store identity</h2><label>HEADLINE</label><input defaultValue="Equipment for the night shift."/><label>ACCENT COLOR</label><div className="color">■ &nbsp; #BAFF32</div><label>CHECKOUT CURRENCIES</label><div className="dual"><button>✓ USDC</button><button>✓ SOL</button></div><label>EMBED SNIPPET</label><pre>{code}</pre><button className="primary wide" onClick={()=>{navigator.clipboard?.writeText(code);notify("Embed code copied")}}>Copy embed code</button></div><div className="preview"><div className="browser">● ● ● <span>nightnode.xyz/store</span></div><div className="mini"><p>NIGHTNODE® / SUPPLY</p><h2>Equipment for<br/>the night shift.</h2><button onClick={open}>SHOP THE DROP →</button><div>{storeSamples.map(p=><article key={p.name}><b>{p.mark}</b><span>{p.name}</span></article>)}</div></div></div></div></>}
function Orders({notify}:any){const data=[["#DN-1048","7xKc…2pQ","Protocol Hoodie","124.00 USDC","Paid"],["#DN-1047","3vPA…9Lm","Midnight Signal Tee","0.44 SOL","In production"],["#DN-1046","G8mA…4Rd","Node Runner Cap","72.00 USDC","Fulfilled"]];return <><Head eyebrow="OPERATIONS" title="Orders" text="Verified payments, production status and fulfillment in one place."><button className="outline">Export CSV</button></Head><Stats/><div className="table orders"><div className="row th"><span>ORDER</span><span>WALLET</span><span>ITEM</span><span>TOTAL</span><span>STATUS</span></div>{data.map((r,i)=><div className="row" key={r[0]}>{r.map((x,j)=><span className={j===4?`state s${i}`:""} key={x}>{x}</span>)}<button onClick={()=>notify(`${r[0]} marked fulfilled`)}>•••</button></div>)}</div></>}
function Payouts({notify}:any){return <><Head eyebrow="TREASURY" title="Payouts" text="Batch project earnings after fulfillment in SOL or USDC."><button className="primary" onClick={()=>notify("Payout scheduled for Friday")}>Schedule payout</button></Head><div className="balance"><div><small>AVAILABLE TO PAY OUT</small><b>$1,742.80</b><span>1,326.50 USDC + 2.64 SOL</span></div><div><small>DESTINATION</small><b>7xKc…2pQ</b><span>Verified project wallet</span></div><button onClick={()=>notify("Demo batch prepared — no funds moved")}>Prepare batch ↗</button></div><h3>PAYOUT HISTORY</h3><div className="table"><div className="payout"><span>Aug 09, 2026</span><span>1,180.00 USDC</span><span>Batch #009</span><strong>Complete</strong></div><div className="payout"><span>Aug 02, 2026</span><span>4.20 SOL</span><span>Batch #008</span><strong>Complete</strong></div></div></>}
function Shop({close,wallet,connect,notify}:any){const [tier,setTier]=useState("Premium"),[size,setSize]=useState("M"),[coin,setCoin]=useState("USDC");const price=tier==="Premium"?52:42;return <div className="modal" onMouseDown={close}><div className="shop" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="shopArt"><span>♜</span><b>D//01</b></div><div className="shopInfo"><p>NIGHTNODE® / DROP 01</p><h2>Midnight Signal Tee</h2><small>Heavyweight everyday uniform. Printed on demand.</small><label>MATERIAL</label><div className="options"><button className={tier==="Standard"?"selected":""} onClick={()=>setTier("Standard")}><b>Standard</b><small>180gsm · 3–5 days</small></button><button className={tier==="Premium"?"selected":""} onClick={()=>setTier("Premium")}><b>Premium +$10</b><small>240gsm · 4–6 days</small></button></div><label>SIZE</label><div className="sizes">{["S","M","L","XL","2XL"].map(x=><button className={size===x?"selected":""} onClick={()=>setSize(x)} key={x}>{x}</button>)}</div><label>PAY WITH</label><div className="dual"><button className={coin==="USDC"?"selected":""} onClick={()=>setCoin("USDC")}>USDC</button><button className={coin==="SOL"?"selected":""} onClick={()=>setCoin("SOL")}>SOL</button></div><div className="total"><span>Total<small>Production estimate included</small></span><b>{coin==="USDC"?`$${price}.00`:`≈ ${(price/165).toFixed(3)} SOL`}</b></div><button className="checkout" onClick={()=>wallet?notify("Demo payment verified on Solana"):connect()}>{wallet?"Pay with connected wallet →":"Connect wallet to checkout"}</button><small className="secure">Payment is verified on-chain before production begins.</small></div></div></div>}
