import {cookies} from "next/headers";import {eq} from "drizzle-orm";import {ensureCoreSchema,getDb} from "@/db";import {projectAdmins,projects} from "@/db/schema";
const DEMO_WALLET="DesignoirsDemoAdmin11111111111111111111111",DEMO_PROJECT="project_nightnode_demo";
async function runtime(){const moduleName="cloudflare:workers";return (await import(moduleName)).env as Record<string,string|undefined>}
function b64(bytes:Uint8Array){let v="";for(const b of bytes)v+=String.fromCharCode(b);return btoa(v).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
async function hmac(value:string){const secret=(await runtime()).AUTH_SECRET||"local-preview-secret-not-for-production";const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64(new Uint8Array(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value))))}
export async function createWalletSession(wallet:string){const expires=Date.now()+604800000,payload=`${wallet}.${expires}`;return `${payload}.${await hmac(payload)}`}
async function walletFromSession(){const value=(await cookies()).get("designoirs_session")?.value;if(!value)return null;const parts=value.split(".");if(parts.length!==3)return null;const [wallet,expires,signature]=parts;if(Number(expires)<Date.now())return null;return signature===await hmac(`${wallet}.${expires}`)?wallet:null}
export async function resolveProjectContext(){await ensureCoreSchema();const db=await getDb();let wallet=await walletFromSession();if(!wallet&&(await runtime()).ALLOW_DEMO_MODE!=="false")wallet=DEMO_WALLET;if(!wallet)throw new Response("Connect and sign in with Phantom or Solflare.",{status:401});if(wallet===DEMO_WALLET){await db.insert(projects).values({id:DEMO_PROJECT,name:"Nightnode",ticker:"NITE",ownerWallet:wallet,payoutWallet:wallet,storefrontConfig:{accent:"#baff32"},createdAt:Date.now()}).onConflictDoNothing();await db.insert(projectAdmins).values({id:`admin_${DEMO_PROJECT}`,projectId:DEMO_PROJECT,wallet,role:"owner"}).onConflictDoNothing()}const [admin]=await db.select().from(projectAdmins).where(eq(projectAdmins.wallet,wallet)).limit(1);if(!admin)throw new Response("This wallet is not assigned to a Designoirs project.",{status:403});return{db,wallet,projectId:admin.projectId}}
export async function provisionWalletProject(wallet:string){await ensureCoreSchema();const db=await getDb();const existing=await db.select().from(projectAdmins).where(eq(projectAdmins.wallet,wallet)).limit(1);if(existing[0])return existing[0].projectId;const projectId=`project_${crypto.randomUUID()}`;await db.insert(projects).values({id:projectId,name:"My Solana Project",ticker:"DROP",ownerWallet:wallet,payoutWallet:wallet,storefrontConfig:{accent:"#baff32"},createdAt:Date.now()});await db.insert(projectAdmins).values({id:crypto.randomUUID(),projectId,wallet,role:"owner"});return projectId}
export function apiError(error:unknown){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Unexpected error"},{status:500})}
