import{integer,real,sqliteTable,text}from"drizzle-orm/sqlite-core";
export const projects=sqliteTable("projects",{id:text("id").primaryKey(),name:text("name").notNull(),ticker:text("ticker"),ownerWallet:text("owner_wallet").notNull(),payoutWallet:text("payout_wallet").notNull(),storefrontConfig:text("storefront_config",{mode:"json"}),createdAt:integer("created_at").notNull()});
export const projectAdmins=sqliteTable("project_admins",{id:text("id").primaryKey(),projectId:text("project_id").notNull(),wallet:text("wallet").notNull(),role:text("role").notNull()});
export const assets=sqliteTable("assets",{id:text("id").primaryKey(),projectId:text("project_id").notNull(),kind:text("kind").notNull(),storageKey:text("storage_key").notNull(),prompt:text("prompt"),locked:integer("locked",{mode:"boolean"}).notNull()});
export const products=sqliteTable("products",{id:text("id").primaryKey(),projectId:text("project_id").notNull(),name:text("name").notNull(),basePrice:real("base_price").notNull(),inventoryMode:text("inventory_mode").notNull(),status:text("status").notNull()});
export const productVariants=sqliteTable("product_variants",{id:text("id").primaryKey(),projectId:text("project_id").notNull(),productId:text("product_id").notNull(),tier:text("tier").notNull(),size:text("size").notNull(),priceDelta:real("price_delta").notNull(),productionDays:integer("production_days").notNull(),providerSku:text("provider_sku")});
export const orders=sqliteTable("orders",{id:text("id").primaryKey(),projectId:text("project_id").notNull(),customerWallet:text("customer_wallet").notNull(),currency:text("currency").notNull(),subtotal:real("subtotal").notNull(),platformFee:real("platform_fee").notNull(),txSignature:text("tx_signature"),status:text("status").notNull(),createdAt:integer("created_at").notNull()});
export const orderItems=sqliteTable("order_items",{id:text("id").primaryKey(),projectId:text("project_id").notNull(),orderId:text("order_id").notNull(),variantId:text("variant_id").notNull(),quantity:integer("quantity").notNull(),unitPrice:real("unit_price").notNull()});
export const payouts=sqliteTable("payouts",{id:text("id").primaryKey(),projectId:text("project_id").notNull(),currency:text("currency").notNull(),amount:real("amount").notNull(),wallet:text("wallet").notNull(),txSignature:text("tx_signature"),status:text("status").notNull(),scheduledAt:integer("scheduled_at")});
